# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Test Site
email: 
description: >- # this means to ignore newlines until "baseurl:"
    Test Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  yokikim
footnote_backlink: "up"
footnote_backlink_inline: yes

# Build settings
theme: minima
plugins:
  - jekyll-admin
#  - jekyll-feed
#  - jekyll-redirect-from
  - jekyll-coffeescript
#  - jekyll-titles-from-headings
#  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-wikilinks
  - jekyll-include-cache
  
whitelist:
  - jekyll-admin
#  - jekyll-redirect-from
  - jekyll-coffeescript
#  - jekyll-titles-from-headings
#  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-wikilinks
  - jekyll-include-cache
  
jekyll_admin:
  homepage: ""
  hidden_links:


wikilinks:
  attributes:
    enabled: true
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []
 
# remote_theme: raghudotcc/simply-jekyll

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
